version: "3.7"
services:
  web:
    image: san4ezshadow/alpine-nginx:1.0
    container_name: web
    depends_on:
        - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/application
    ports:
        - "8082:80"
    networks:
      www_net:

  php:
    image: san4ezshadow/alpine-php:1.0
    container_name: php
    volumes:
      - ./application:/var/application
    networks:
      www_net:

networks:
  www_net:
